//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5477
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IVendorManagement")]
public interface IVendorManagement
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVendorManagement/CreateUser", ReplyAction="http://tempuri.org/IVendorManagement/CreateUserResponse")]
    int CreateUser(string externalUserID, string vendorName, string firstName, string lastName, string email, string phone);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVendorManagement/CheckUser", ReplyAction="http://tempuri.org/IVendorManagement/CheckUserResponse")]
    int? CheckUser(string externaUserID, string vendorName);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IVendorManagementChannel : IVendorManagement, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class VendorManagementClient : System.ServiceModel.ClientBase<IVendorManagement>, IVendorManagement
{
    
    public VendorManagementClient()
    {
    }
    
    public VendorManagementClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public VendorManagementClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public VendorManagementClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public VendorManagementClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public int CreateUser(string externalUserID, string vendorName, string firstName, string lastName, string email, string phone)
    {
        return base.Channel.CreateUser(externalUserID, vendorName, firstName, lastName, email, phone);
    }
    
    public int? CheckUser(string externaUserID, string vendorName)
    {
        return base.Channel.CheckUser(externaUserID, vendorName);
    }
}
